
const DATA_LAKE = [
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "dog", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "vegtables", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "fruit", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "gym", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "gym", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "gym", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "gym", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "gym", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},
    { name: "Dog", tag: "food", substitle: "Labrador", url: "www.google.com", text: "lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem", image: ["https://cdn.wallpapersafari.com/59/60/SBwHrV.jpg"]},    
]

class DB {
    constructor() {
        this.data = DATA_LAKE;
        this.randomlySortData();
    }

    getData () {
        return this.data;
    }

    randomlySortData() {
        return this.data.sort(() => Math.random() - 0.5);
    }

    getByTag(tag) {
        return this.data.filter(item => item.tag === tag);
    }

    //get all distinct tags
    getAllTags() {
        const tags = this.data.map(item => item.tag);
        const uniqueTags = [...new Set(tags)];
        return uniqueTags;
    }

    getIndexByTag(tag) {
        const indexes = [];
        this.data.forEach((item, index) => {
            if (item.tag === tag) {
                indexes.push(index);
            }
        })
        if (indexes.length === 0) {
            return this.data;
        }
        return indexes;
    }
    
    incrementIndex(index) {
        if (index + 1 >= this.data.length) {
            return 0;
        }
        return index + 1;
    }

    decrementIndex(index) {
        if (index - 1 < 0) {
            return this.data.length - 1;
        } 
        return index - 1;
    }

    getByIndex(index) {
        return this.data[index];
    }

    getNextData(index) {
        return this.data[this.incrementIndex(index)];
    }

    getPrevData(index) {
        return this.data[this.decrementIndex(index)];
    }

    getTenAboveAndBelow(index) {
        index = parseInt(index);
        const padding = 2;
        const maxIndex = this.data.length;
        let indexes = [];
        for (let i = -padding; i <= padding; i++) {
            let currIndex = index + i;
            if (currIndex < 0) {
                currIndex += maxIndex;
            } else if (currIndex >= maxIndex) {
                currIndex -= maxIndex;
            }
            indexes.push(currIndex);
        }
        const dataFromIndexes = [];
        indexes.forEach(index => {
            dataFromIndexes.push(this.data[index]);
        });
        return dataFromIndexes;
    }
}




const db = new DB();
export default db;